// Downloads the Google Fonts used by the app into src/renderer/fonts/ and emits a
// local @font-face stylesheet, so a bundled APK renders correctly with no network.
// Run once (or after changing the list): node scripts/fetch-fonts.js
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const fontsDir = path.join(rootDir, 'src/renderer/fonts');

// A modern UA is required or Google serves ttf instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

    const FAMILIES = [
    { family: 'Amiri', weights: [400, 700], italics: [400] },
    { family: 'Scheherazade New', weights: [400, 700], italics: [] },
    { family: 'Cairo', weights: [400, 600, 700, 800], italics: [] }
];

// Only these subsets are shipped: Arabic for the Quran text, Latin for the UI.
const KEEP_SUBSETS = ['arabic', 'latin'];

function buildCssUrl(spec) {
    const name = encodeURIComponent(spec.family).replace(/%20/g, '+');
    let axis;
    if (spec.italics.length) {
        // Both axes present: tuples must be "ital,wght" pairs, in order.
        const normal = spec.weights.map(w => `0,${w}`);
        const italic = spec.italics.map(w => `1,${w}`);
        axis = `ital,wght@${[...normal, ...italic].join(';')}`;
    } else {
        axis = `wght@${spec.weights.join(';')}`;
    }
    return `https://fonts.googleapis.com/css2?family=${name}:${axis}&display=swap`;
}

function parseFaces(css) {
    const faces = [];
    const blocks = css.split('@font-face').slice(1);
    for (const block of blocks) {
        const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
        const style = (block.match(/font-style:\s*([^;]+);/) || [])[1] || 'normal';
        const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1] || '400';
        const url = (block.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
        const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
        if (!family || !url) continue;

        // Google orders the unicode-range blocks; match the subset by its first few code points.
        const subset = detectSubset(range);
        if (!KEEP_SUBSETS.includes(subset)) continue;

        faces.push({ family, style: style.trim(), weight: weight.trim(), url, subset });
    }
    return faces;
}

function detectSubset(range) {
    if (!range) return 'other';
    // Order matters:
    //  - the core `arabic` range starts at U+0600 and also contains U+0750
    //  - `arabic-ext` has U+0750.. but no U+0600
    //  - `latin-ext` also contains U+0000, so it must be tested first
    if (range.includes('U+0600')) return 'arabic';
    if (range.includes('U+0750') || range.includes('U+08A0') || range.includes('U+FB50')) return 'arabic-ext';
    if (range.includes('U+0100') || range.includes('U+1E00') || range.includes('U+2C60')) return 'latin-ext';
    if (range.includes('U+0000')) return 'latin';
    return 'other';
}

async function main() {
    if (!fs.existsSync(fontsDir)) fs.mkdirSync(fontsDir, { recursive: true });

    const all = [];

    for (const spec of FAMILIES) {
        const url = buildCssUrl(spec);
        process.stdout.write(`→ ${spec.family} ... `);
        const res = await fetch(url, { headers: { 'User-Agent': UA } });
        if (!res.ok) throw new Error(`${spec.family}: HTTP ${res.status}`);
        const css = await res.text();
        const faces = parseFaces(css);
        all.push(...faces);
        process.stdout.write(`${faces.length} file(s)\n`);
    }

    let out = `/* Local font bundle - generated by scripts/fetch-fonts.js. Do not edit by hand.\n   The Android build ships these so the app renders correctly offline. */\n\n`;

    // Google emits several unicode-range blocks per file; dedupe by output name.
    const emitted = new Set();

    for (const face of all) {
        const fileName = `${face.family.toLowerCase().replace(/\s+/g, '-')}-${face.weight}-${face.style}-${face.subset}.woff2`;
        if (emitted.has(fileName)) continue;
        emitted.add(fileName);

        const dest = path.join(fontsDir, fileName);

        if (!fs.existsSync(dest)) {
            const res = await fetch(face.url, { headers: { 'User-Agent': UA } });
            if (!res.ok) throw new Error(`${fileName}: HTTP ${res.status}`);
            fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
        }

        out += `@font-face {\n`
            + `    font-family: '${face.family}';\n`
            + `    font-style: ${face.style};\n`
            + `    font-weight: ${face.weight};\n`
            + `    font-display: swap;\n`
            + `    src: url('../fonts/${fileName}') format('woff2');\n`
            + `}\n\n`;
    }

    fs.writeFileSync(path.join(rootDir, 'src/renderer/css/fonts.css'), out);

    const total = fs.readdirSync(fontsDir)
        .reduce((sum, f) => sum + fs.statSync(path.join(fontsDir, f)).size, 0);
    console.log(`\n✅ ${emitted.size} font files, ${(total / 1024 / 1024).toFixed(2)} MB total`);
    console.log('   -> src/renderer/css/fonts.css');
}

main().catch((err) => {
    console.error('❌ Font download failed:', err);
    process.exit(1);
});
